#!/usr/bin/env python3
"""
KSEB Energy Analytics - Windows Executable Build Script

This script automates the conversion of the full-stack webapp into a Windows desktop application.

Requirements (Development Machine):
- Python 3.11+
- Node.js 18+
- PyInstaller
- NSIS (Nullsoft Scriptable Install System)

Output:
- KSEB-Setup.exe (Windows installer with bundled dependencies)

Usage:
    python build_windows_exe.py [--clean] [--skip-backend] [--skip-frontend] [--skip-installer]
"""

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path
import json

class Colors:
    """Terminal colors for output."""
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def print_header(message):
    """Print formatted header."""
    print(f"\n{Colors.HEADER}{Colors.BOLD}{'='*80}{Colors.ENDC}")
    print(f"{Colors.HEADER}{Colors.BOLD}{message.center(80)}{Colors.ENDC}")
    print(f"{Colors.HEADER}{Colors.BOLD}{'='*80}{Colors.ENDC}\n")

def print_step(step_num, message):
    """Print formatted step."""
    print(f"{Colors.OKBLUE}{Colors.BOLD}[Step {step_num}]{Colors.ENDC} {message}")

def print_success(message):
    """Print success message."""
    print(f"{Colors.OKGREEN}✓ {message}{Colors.ENDC}")

def print_error(message):
    """Print error message."""
    print(f"{Colors.FAIL}✗ {message}{Colors.ENDC}")

def print_warning(message):
    """Print warning message."""
    print(f"{Colors.WARNING}⚠ {message}{Colors.ENDC}")

def run_command(command, cwd=None, env=None):
    """Run shell command and return success status."""
    try:
        print(f"  → Running: {' '.join(command) if isinstance(command, list) else command}")
        result = subprocess.run(
            command,
            cwd=cwd,
            env=env,
            shell=True if isinstance(command, str) else False,
            check=True,
            capture_output=True,
            text=True
        )
        if result.stdout:
            print(f"    {result.stdout}")
        return True
    except subprocess.CalledProcessError as e:
        print_error(f"Command failed: {e}")
        if e.stderr:
            print(f"    Error: {e.stderr}")
        return False

class WindowsBuilder:
    """Main builder class for Windows executable."""

    def __init__(self, project_root, clean=False):
        self.project_root = Path(project_root).resolve()
        self.backend_dir = self.project_root / "backend_fastapi"
        self.frontend_dir = self.project_root / "frontend"
        self.build_dir = self.project_root / "build"
        self.dist_dir = self.project_root / "dist"
        self.installer_dir = self.project_root / "installer"

        if clean:
            self.clean_build()

    def clean_build(self):
        """Clean previous build artifacts."""
        print_step(0, "Cleaning previous build artifacts...")

        dirs_to_clean = [self.build_dir, self.dist_dir, self.installer_dir / "Output"]

        for dir_path in dirs_to_clean:
            if dir_path.exists():
                print(f"  → Removing {dir_path}")
                shutil.rmtree(dir_path)

        print_success("Build directories cleaned")

    def check_prerequisites(self):
        """Check if all required tools are installed."""
        print_step(1, "Checking prerequisites...")

        checks = {
            "Python": ["python", "--version"],
            "Node.js": ["node", "--version"],
            "npm": ["npm", "--version"],
            "PyInstaller": ["pyinstaller", "--version"],
        }

        all_ok = True
        for tool, command in checks.items():
            try:
                result = subprocess.run(command, capture_output=True, text=True, check=True)
                version = result.stdout.strip().split('\n')[0]
                print_success(f"{tool}: {version}")
            except (subprocess.CalledProcessError, FileNotFoundError):
                print_error(f"{tool} not found!")
                all_ok = False

        if not all_ok:
            print_error("Missing prerequisites. Install them first:")
            print("  pip install pyinstaller")
            print("  Download Node.js from https://nodejs.org/")
            sys.exit(1)

        print_success("All prerequisites satisfied")

    def create_pyinstaller_spec(self):
        """Create PyInstaller spec file for backend."""
        print_step(2, "Creating PyInstaller spec file...")

        spec_content = '''# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for KSEB Energy Analytics Backend
Automatically generated by build_windows_exe.py
"""

block_cipher = None

a = Analysis(
    ['backend_fastapi/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('backend_fastapi/input', 'input'),  # Embed Excel templates
        ('backend_fastapi/models', 'models'),  # Embed model files
    ],
    hiddenimports=[
        # Core FastAPI
        'fastapi',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'pydantic',
        'starlette',

        # Data processing
        'pandas',
        'numpy',
        'scipy',
        'scipy.special',
        'scipy.special.cython_special',
        'scipy.linalg',
        'scipy.sparse',
        'scipy.sparse.csgraph',
        'scipy.sparse.linalg',
        'scipy.optimize',
        'scipy.interpolate',

        # Machine learning
        'sklearn',
        'sklearn.ensemble',
        'sklearn.linear_model',
        'sklearn.preprocessing',
        'sklearn.metrics',
        'sklearn.model_selection',
        'statsmodels',
        'statsmodels.api',
        'statsmodels.tsa',
        'statsmodels.tsa.api',

        # Grid optimization
        'pypsa',
        'xarray',
        'netCDF4',
        'cftime',

        # Visualization
        'matplotlib',
        'matplotlib.pyplot',
        'seaborn',
        'plotly',
        'plotly.graph_objs',

        # File handling
        'openpyxl',
        'openpyxl.cell',
        'openpyxl.cell.cell',
        'xlsxwriter',

        # Utilities
        'httpx',
        'dateutil',
        'holidays',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'pydoc',
        'PIL',
        'setuptools',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='kseb-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,  # Compress with UPX
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # No console window for production
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
'''

        spec_file = self.project_root / "backend.spec"
        spec_file.write_text(spec_content)
        print_success(f"Created {spec_file}")

    def build_backend(self):
        """Build backend executable with PyInstaller."""
        print_step(3, "Building backend executable...")

        # Create spec file
        self.create_pyinstaller_spec()

        # Install backend dependencies
        print("  → Installing backend dependencies...")
        if not run_command(
            ["pip", "install", "-r", "requirements.txt"],
            cwd=self.backend_dir
        ):
            print_error("Failed to install backend dependencies")
            return False

        # Run PyInstaller
        print("  → Running PyInstaller (this may take 5-10 minutes)...")
        if not run_command(
            ["pyinstaller", "--clean", "backend.spec"],
            cwd=self.project_root
        ):
            print_error("PyInstaller build failed")
            return False

        backend_exe = self.dist_dir / "kseb-backend.exe"
        if backend_exe.exists():
            size_mb = backend_exe.stat().st_size / (1024 * 1024)
            print_success(f"Backend executable created: {backend_exe} ({size_mb:.1f} MB)")
            return True
        else:
            print_error("Backend executable not found")
            return False

    def create_electron_files(self):
        """Create Electron wrapper files for frontend."""
        print_step(4, "Creating Electron wrapper files...")

        # Create electron-main.js
        electron_main = self.frontend_dir / "electron-main.js"
        electron_main_content = '''const { app, BrowserWindow, Menu } = require('electron');
const path = require('path');
const axios = require('axios');
const { spawn } = require('child_process');

let mainWindow;
let backendProcess = null;
const BACKEND_PORT = 8000;
const MAX_WAIT_TIME = 30000; // 30 seconds

// Start backend process
function startBackend() {
  return new Promise((resolve, reject) => {
    const backendExe = path.join(process.resourcesPath, 'backend', 'kseb-backend.exe');

    console.log('Starting backend:', backendExe);

    backendProcess = spawn(backendExe, [], {
      detached: false,
      stdio: 'ignore',
      windowsHide: true
    });

    backendProcess.on('error', (error) => {
      console.error('Backend process error:', error);
      reject(error);
    });

    resolve();
  });
}

// Wait for backend to be ready
async function waitForBackend(maxAttempts = 30) {
  console.log('Waiting for backend to be ready...');

  for (let i = 0; i < maxAttempts; i++) {
    try {
      const response = await axios.get(`http://localhost:${BACKEND_PORT}/health`, {
        timeout: 1000
      });

      if (response.status === 200) {
        console.log('Backend is ready!');
        return true;
      }
    } catch (error) {
      // Backend not ready yet, wait
      console.log(`Attempt ${i + 1}/${maxAttempts}: Backend not ready...`);
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
  }

  return false;
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 900,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: false,
      contextIsolation: true
    },
    icon: path.join(__dirname, 'icon.png'),
    title: 'KSEB Energy Analytics'
  });

  // Load the production build
  mainWindow.loadFile(path.join(__dirname, 'dist', 'index.html'));

  // Update API URL to point to backend
  mainWindow.webContents.executeJavaScript(`
    window.BACKEND_URL = 'http://localhost:${BACKEND_PORT}';
  `);

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// Create application menu
function createMenu() {
  const template = [
    {
      label: 'File',
      submenu: [
        { role: 'quit' }
      ]
    },
    {
      label: 'Edit',
      submenu: [
        { role: 'undo' },
        { role: 'redo' },
        { type: 'separator' },
        { role: 'cut' },
        { role: 'copy' },
        { role: 'paste' }
      ]
    },
    {
      label: 'View',
      submenu: [
        { role: 'reload' },
        { role: 'forceReload' },
        { type: 'separator' },
        { role: 'resetZoom' },
        { role: 'zoomIn' },
        { role: 'zoomOut' }
      ]
    }
  ];

  const menu = Menu.buildFromTemplate(template);
  Menu.setApplicationMenu(menu);
}

app.on('ready', async () => {
  try {
    // Start backend
    await startBackend();

    // Wait for backend to be ready
    const backendReady = await waitForBackend();

    if (!backendReady) {
      console.error('Backend failed to start within timeout');
      app.quit();
      return;
    }

    // Create window and menu
    createMenu();
    createWindow();

  } catch (error) {
    console.error('Error during startup:', error);
    app.quit();
  }
});

app.on('window-all-closed', () => {
  // Terminate backend process
  if (backendProcess) {
    backendProcess.kill();
  }

  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (mainWindow === null) {
    createWindow();
  }
});

// Clean up on app quit
app.on('quit', () => {
  if (backendProcess) {
    backendProcess.kill();
  }
});
'''
        electron_main.write_text(electron_main_content)
        print_success("Created electron-main.js")

        # Create preload.js
        preload_js = self.frontend_dir / "preload.js"
        preload_content = '''const { contextBridge } = require('electron');

// Expose protected methods that allow the renderer process to use
// ipcRenderer without exposing the entire object
contextBridge.exposeInMainWorld('electron', {
  platform: process.platform,
  version: process.versions.electron
});
'''
        preload_js.write_text(preload_content)
        print_success("Created preload.js")

        # Update package.json
        package_json_path = self.frontend_dir / "package.json"
        with open(package_json_path, 'r') as f:
            package_json = json.load(f)

        # Add electron configuration
        package_json['main'] = 'electron-main.js'
        package_json['build'] = {
            "appId": "com.kseb.analytics",
            "productName": "KSEB Energy Analytics",
            "directories": {
                "output": "../dist"
            },
            "files": [
                "dist/**/*",
                "electron-main.js",
                "preload.js"
            ],
            "extraResources": [
                {
                    "from": "../dist/kseb-backend.exe",
                    "to": "backend/kseb-backend.exe"
                }
            ],
            "win": {
                "target": "portable",
                "icon": "icon.ico"
            }
        }

        # Add electron dependencies
        if 'devDependencies' not in package_json:
            package_json['devDependencies'] = {}

        package_json['devDependencies']['electron'] = '^28.0.0'
        package_json['devDependencies']['electron-builder'] = '^24.9.1'

        # Add axios to dependencies
        if 'dependencies' not in package_json:
            package_json['dependencies'] = {}

        package_json['dependencies']['axios'] = '^1.12.2'

        # Add build scripts
        if 'scripts' not in package_json:
            package_json['scripts'] = {}

        package_json['scripts']['electron:build'] = 'electron-builder'

        with open(package_json_path, 'w') as f:
            json.dump(package_json, f, indent=2)

        print_success("Updated package.json with Electron configuration")

    def build_frontend(self):
        """Build frontend executable with Electron."""
        print_step(5, "Building frontend executable...")

        # Create Electron files
        self.create_electron_files()

        # Install frontend dependencies
        print("  → Installing frontend dependencies (this may take 3-5 minutes)...")
        if not run_command(["npm", "install"], cwd=self.frontend_dir):
            print_error("Failed to install frontend dependencies")
            return False

        # Build React app with Vite
        print("  → Building React app with Vite...")
        if not run_command(["npm", "run", "build"], cwd=self.frontend_dir):
            print_error("Failed to build React app")
            return False

        # Build Electron app
        print("  → Building Electron app (this may take 5-10 minutes)...")
        if not run_command(["npm", "run", "electron:build"], cwd=self.frontend_dir):
            print_error("Failed to build Electron app")
            return False

        frontend_exe = self.dist_dir / "KSEB Energy Analytics.exe"
        if frontend_exe.exists():
            size_mb = frontend_exe.stat().st_size / (1024 * 1024)
            print_success(f"Frontend executable created: {frontend_exe} ({size_mb:.1f} MB)")
            return True
        else:
            print_error("Frontend executable not found")
            return False

    def create_installer(self):
        """Create Windows installer with NSIS."""
        print_step(6, "Creating Windows installer...")

        # Check if NSIS is installed
        try:
            subprocess.run(["makensis", "-VERSION"], capture_output=True, check=True)
        except (subprocess.CalledProcessError, FileNotFoundError):
            print_warning("NSIS not found. Skipping installer creation.")
            print("  Download NSIS from https://nsis.sourceforge.io/")
            print("  Or use the portable executable from dist/ folder")
            return True

        # Create installer directory
        self.installer_dir.mkdir(exist_ok=True)

        # Create NSIS script
        nsis_script = self.installer_dir / "installer.nsi"
        nsis_content = f'''!include "MUI2.nsh"

; Application info
Name "KSEB Energy Analytics"
OutFile "KSEB-Setup.exe"
InstallDir "$PROGRAMFILES\\KSEB Energy Analytics"
RequestExecutionLevel admin

; Interface settings
!define MUI_ABORTWARNING

; Pages
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; Languages
!insertmacro MUI_LANGUAGE "English"

; Installation section
Section "Install"
  SetOutPath "$INSTDIR"

  ; Copy executable
  File "{self.dist_dir}\\KSEB Energy Analytics.exe"

  ; Create application data directories
  CreateDirectory "$APPDATA\\KSEB Energy Analytics"
  CreateDirectory "$DOCUMENTS\\KSEB Projects"

  ; Create Start Menu shortcuts
  CreateDirectory "$SMPROGRAMS\\KSEB Energy Analytics"
  CreateShortcut "$SMPROGRAMS\\KSEB Energy Analytics\\KSEB Energy Analytics.lnk" "$INSTDIR\\KSEB Energy Analytics.exe"
  CreateShortcut "$SMPROGRAMS\\KSEB Energy Analytics\\Uninstall.lnk" "$INSTDIR\\Uninstall.exe"

  ; Create Desktop shortcut
  CreateShortcut "$DESKTOP\\KSEB Energy Analytics.lnk" "$INSTDIR\\KSEB Energy Analytics.exe"

  ; Create uninstaller
  WriteUninstaller "$INSTDIR\\Uninstall.exe"

  ; Write registry keys for Add/Remove Programs
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\KSEBEnergyAnalytics" "DisplayName" "KSEB Energy Analytics"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\KSEBEnergyAnalytics" "UninstallString" "$INSTDIR\\Uninstall.exe"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\KSEBEnergyAnalytics" "DisplayIcon" "$INSTDIR\\KSEB Energy Analytics.exe"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\KSEBEnergyAnalytics" "Publisher" "KSEB"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\KSEBEnergyAnalytics" "DisplayVersion" "1.0.0"
SectionEnd

; Uninstallation section
Section "Uninstall"
  ; Delete files
  Delete "$INSTDIR\\KSEB Energy Analytics.exe"
  Delete "$INSTDIR\\Uninstall.exe"

  ; Delete shortcuts
  Delete "$SMPROGRAMS\\KSEB Energy Analytics\\KSEB Energy Analytics.lnk"
  Delete "$SMPROGRAMS\\KSEB Energy Analytics\\Uninstall.lnk"
  Delete "$DESKTOP\\KSEB Energy Analytics.lnk"

  ; Remove directories
  RMDir "$SMPROGRAMS\\KSEB Energy Analytics"
  RMDir "$INSTDIR"

  ; Remove registry keys
  DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\KSEBEnergyAnalytics"

  ; Optional: Ask to remove user data
  MessageBox MB_YESNO "Do you want to remove all project data and settings?" IDNO skip_data
  RMDir /r "$APPDATA\\KSEB Energy Analytics"
  RMDir /r "$DOCUMENTS\\KSEB Projects"
  skip_data:
SectionEnd
'''
        nsis_script.write_text(nsis_content)
        print_success("Created NSIS installer script")

        # Run NSIS
        print("  → Running NSIS (this may take 2-3 minutes)...")
        if not run_command(
            ["makensis", str(nsis_script)],
            cwd=self.installer_dir
        ):
            print_error("NSIS build failed")
            return False

        installer_exe = self.installer_dir / "KSEB-Setup.exe"
        if installer_exe.exists():
            size_mb = installer_exe.stat().st_size / (1024 * 1024)
            print_success(f"Installer created: {installer_exe} ({size_mb:.1f} MB)")
            return True
        else:
            print_error("Installer not found")
            return False

    def print_summary(self):
        """Print build summary."""
        print_header("BUILD SUMMARY")

        print(f"{Colors.BOLD}Build artifacts:{Colors.ENDC}")

        artifacts = [
            ("Backend executable", self.dist_dir / "kseb-backend.exe"),
            ("Frontend executable", self.dist_dir / "KSEB Energy Analytics.exe"),
            ("Installer", self.installer_dir / "KSEB-Setup.exe"),
        ]

        total_size = 0
        for name, path in artifacts:
            if path.exists():
                size_mb = path.stat().st_size / (1024 * 1024)
                total_size += size_mb
                print(f"  ✓ {name}: {path} ({size_mb:.1f} MB)")
            else:
                print(f"  ✗ {name}: Not found")

        print(f"\n{Colors.BOLD}Total size: {total_size:.1f} MB{Colors.ENDC}")

        print(f"\n{Colors.BOLD}Next steps:{Colors.ENDC}")
        print("  1. Test the executable on a clean Windows machine (no Python/Node.js)")
        print("  2. Verify all 105 API endpoints work")
        print("  3. Test Excel file operations")
        print("  4. Test forecasting and PyPSA optimization")
        print("  5. Distribute KSEB-Setup.exe to end users")

    def build(self, skip_backend=False, skip_frontend=False, skip_installer=False):
        """Main build method."""
        print_header("KSEB ENERGY ANALYTICS - WINDOWS BUILD")

        self.check_prerequisites()

        if not skip_backend:
            if not self.build_backend():
                print_error("Backend build failed")
                sys.exit(1)

        if not skip_frontend:
            if not self.build_frontend():
                print_error("Frontend build failed")
                sys.exit(1)

        if not skip_installer:
            self.create_installer()

        self.print_summary()

        print_success("\nBuild completed successfully!")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Build KSEB Energy Analytics as Windows executable"
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Clean previous build artifacts before building"
    )
    parser.add_argument(
        "--skip-backend",
        action="store_true",
        help="Skip backend build"
    )
    parser.add_argument(
        "--skip-frontend",
        action="store_true",
        help="Skip frontend build"
    )
    parser.add_argument(
        "--skip-installer",
        action="store_true",
        help="Skip installer creation"
    )

    args = parser.parse_args()

    # Get project root (assuming script is in project root)
    project_root = Path(__file__).parent.resolve()

    # Create builder and run
    builder = WindowsBuilder(project_root, clean=args.clean)
    builder.build(
        skip_backend=args.skip_backend,
        skip_frontend=args.skip_frontend,
        skip_installer=args.skip_installer
    )


if __name__ == "__main__":
    main()
